settings:
  base_path: "<PATH HERE>"                  # Path to your repository, will be considered as the root directory
  branch: "main"                            # Branch for dependabot updates
  intervals:                                # Update intervals for each ecosystem (OPTIONS: "daily", "weekly", "monthly")
    pip: "daily"
    npm: "daily"
    docker: "daily"
    github-actions: "daily"
    gradle: "weekly"
  pull_requests_limit: 10                   # Limit on open pull requests per ecosystem
  ignored_paths:                            # Paths that will not be included in the scan
    - "**/node_modules/**"
    - dist
    - build
    - .git
    - "**/__pycache__"
    - "**/temp/**"
    - backend/generated-files/
  grouping_strategy: "package-ecosystem"    # OPTIONS: "none", "package-ecosystem", "custom"
  custom_groups:
    - name: "core-packages"
      directories:
        - "../<sample path 1>"
        - "../<sample path 2>"
    - name: "feature-packages"
      directories:
        - "../<sample path 3>"
        - "../<sample path 4>"